spring:
  datasource:

#    url: jdbc:h2:mem:testdb//localhost:5432/h2:

    url: jdbc:h2:mem:default
    driverClassName: org.h2.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
